### ISSUE TITLE
Logging correct params from ApplyFeatureTable catch 

### ISSUE THREAD

**Issue by amommendes** [feast-dev/feast-java#5]
## Expected Behavior 
No biggie: Logging correct project name and table name order when `ApplyFeatureTable` request is wrong.

```
core_1  | 2021-02-23 17:54:55.355 ERROR 001d9c591f60 --- [ault-executor-6] f.c.g.CoreServiceImpl: ApplyFeatureTable: Invalid apply Feature Table Request: (name: default, project: Driver Statistics)
```

## Current Behavior
The table name is printed in the place of the project name, [here](https://github.com/feast-dev/feast-java/blob/ee23a9c7721e309ec89637eeac7522d7c9fd38b3/core/src/main/java/feast/core/grpc/CoreServiceImpl.java#L321) and [here](https://github.com/feast-dev/feast-java/blob/ee23a9c7721e309ec89637eeac7522d7c9fd38b3/core/src/main/java/feast/core/grpc/CoreServiceImpl.java#L314)
 
### Specifications

- Version: gcr.io/kf-feast/feast-core:develop
- Platform: docker

**Comment by woop** [comment]
Thanks @amommendes!
